language: node_js
node_js:
  - '16'

before_install:
  - npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
  - npm install
  - npm run fetch:types

script:
  - npm run build
  - npm run test:report

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm_config_yes=true npx -p @qiwi/semrel-toolkit semrel
