window.esdocSearchIndex = [
  [
    "reqresnext/src/main/js/response.js~default_cookies",
    "variable/index.html#static-variable-DEFAULT_COOKIES",
    "<span>DEFAULT_COOKIES</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/response.js</span>",
    "variable"
  ],
  [
    "reqresnext/src/main/js/response.js~default_headers",
    "variable/index.html#static-variable-DEFAULT_HEADERS",
    "<span>DEFAULT_HEADERS</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/response.js</span>",
    "variable"
  ],
  [
    "reqresnext/src/main/js/response.js~default_req",
    "variable/index.html#static-variable-DEFAULT_REQ",
    "<span>DEFAULT_REQ</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/response.js</span>",
    "variable"
  ],
  [
    "reqresnext/src/main/js/response.js~default_status_code",
    "variable/index.html#static-variable-DEFAULT_STATUS_CODE",
    "<span>DEFAULT_STATUS_CODE</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/response.js</span>",
    "variable"
  ],
  [
    "reqresnext/src/main/js/request.js~reqoptions",
    "class/src/main/js/request.js~ReqOptions.html",
    "<span>ReqOptions</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/request.js</span>",
    "class"
  ],
  [
    "reqresnext/src/main/js/request.js~request",
    "class/src/main/js/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/request.js</span>",
    "class"
  ],
  [
    "reqresnext/src/main/js/response.js~resoptions",
    "class/src/main/js/response.js~ResOptions.html",
    "<span>ResOptions</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/response.js</span>",
    "class"
  ],
  [
    "reqresnext/src/main/js/response.js~response",
    "class/src/main/js/response.js~Response.html",
    "<span>Response</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/response.js</span>",
    "class"
  ],
  [
    "reqresnext/src/main/js/util.js~appendadditionalprops",
    "function/index.html#static-function-appendAdditionalProps",
    "<span>appendAdditionalProps</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/util.js</span>",
    "function"
  ],
  [
    "reqresnext/src/main/js/util.js~concat",
    "function/index.html#static-function-concat",
    "<span>concat</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/util.js</span>",
    "function"
  ],
  [
    "reqresnext/src/main/js/reqresnext.js~gen",
    "function/index.html#static-function-gen",
    "<span>gen</span> <span class=\"search-result-import-path\">reqresnext/src/main/js/reqresnext.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/main/js/app.js",
    "file/src/main/js/app.js.html",
    "src/main/js/app.js",
    "file"
  ],
  [
    "src/main/js/index.js",
    "file/src/main/js/index.js.html",
    "src/main/js/index.js",
    "file"
  ],
  [
    "src/main/js/interface.js",
    "file/src/main/js/interface.js.html",
    "src/main/js/interface.js",
    "file"
  ],
  [
    "src/main/js/reqresnext.js",
    "file/src/main/js/reqresnext.js.html",
    "src/main/js/reqresnext.js",
    "file"
  ],
  [
    "src/main/js/request.js",
    "file/src/main/js/request.js.html",
    "src/main/js/request.js",
    "file"
  ],
  [
    "src/main/js/request.js~reqoptions#app",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-app",
    "src/main/js/request.js~ReqOptions#app",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#body",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-body",
    "src/main/js/request.js~ReqOptions#body",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#connection",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-connection",
    "src/main/js/request.js~ReqOptions#connection",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#constructor",
    "class/src/main/js/request.js~ReqOptions.html#instance-constructor-constructor",
    "src/main/js/request.js~ReqOptions#constructor",
    "method"
  ],
  [
    "src/main/js/request.js~reqoptions#headers",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-headers",
    "src/main/js/request.js~ReqOptions#headers",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#params",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-params",
    "src/main/js/request.js~ReqOptions#params",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#query",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-query",
    "src/main/js/request.js~ReqOptions#query",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#raw",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-raw",
    "src/main/js/request.js~ReqOptions#raw",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#res",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-res",
    "src/main/js/request.js~ReqOptions#res",
    "member"
  ],
  [
    "src/main/js/request.js~reqoptions#socket",
    "class/src/main/js/request.js~ReqOptions.html#instance-member-socket",
    "src/main/js/request.js~ReqOptions#socket",
    "member"
  ],
  [
    "src/main/js/request.js~request#_flush",
    "class/src/main/js/request.js~Request.html#instance-member-_flush",
    "src/main/js/request.js~Request#_flush",
    "member"
  ],
  [
    "src/main/js/request.js~request#_readablestate",
    "class/src/main/js/request.js~Request.html#instance-member-_readableState",
    "src/main/js/request.js~Request#_readableState",
    "member"
  ],
  [
    "src/main/js/request.js~request#app",
    "class/src/main/js/request.js~Request.html#instance-member-app",
    "src/main/js/request.js~Request#app",
    "member"
  ],
  [
    "src/main/js/request.js~request#body",
    "class/src/main/js/request.js~Request.html#instance-member-body",
    "src/main/js/request.js~Request#body",
    "member"
  ],
  [
    "src/main/js/request.js~request#connection",
    "class/src/main/js/request.js~Request.html#instance-member-connection",
    "src/main/js/request.js~Request#connection",
    "member"
  ],
  [
    "src/main/js/request.js~request#constructor",
    "class/src/main/js/request.js~Request.html#instance-constructor-constructor",
    "src/main/js/request.js~Request#constructor",
    "method"
  ],
  [
    "src/main/js/request.js~request#headers",
    "class/src/main/js/request.js~Request.html#instance-member-headers",
    "src/main/js/request.js~Request#headers",
    "member"
  ],
  [
    "src/main/js/request.js~request#params",
    "class/src/main/js/request.js~Request.html#instance-member-params",
    "src/main/js/request.js~Request#params",
    "member"
  ],
  [
    "src/main/js/request.js~request#res",
    "class/src/main/js/request.js~Request.html#instance-member-res",
    "src/main/js/request.js~Request#res",
    "member"
  ],
  [
    "src/main/js/request.js~request#socket",
    "class/src/main/js/request.js~Request.html#instance-member-socket",
    "src/main/js/request.js~Request#socket",
    "member"
  ],
  [
    "src/main/js/response.js",
    "file/src/main/js/response.js.html",
    "src/main/js/response.js",
    "file"
  ],
  [
    "src/main/js/response.js~resoptions#app",
    "class/src/main/js/response.js~ResOptions.html#instance-member-app",
    "src/main/js/response.js~ResOptions#app",
    "member"
  ],
  [
    "src/main/js/response.js~resoptions#constructor",
    "class/src/main/js/response.js~ResOptions.html#instance-constructor-constructor",
    "src/main/js/response.js~ResOptions#constructor",
    "method"
  ],
  [
    "src/main/js/response.js~resoptions#cookies",
    "class/src/main/js/response.js~ResOptions.html#instance-member-cookies",
    "src/main/js/response.js~ResOptions#cookies",
    "member"
  ],
  [
    "src/main/js/response.js~resoptions#headers",
    "class/src/main/js/response.js~ResOptions.html#instance-member-headers",
    "src/main/js/response.js~ResOptions#headers",
    "member"
  ],
  [
    "src/main/js/response.js~resoptions#raw",
    "class/src/main/js/response.js~ResOptions.html#instance-member-raw",
    "src/main/js/response.js~ResOptions#raw",
    "member"
  ],
  [
    "src/main/js/response.js~resoptions#req",
    "class/src/main/js/response.js~ResOptions.html#instance-member-req",
    "src/main/js/response.js~ResOptions#req",
    "member"
  ],
  [
    "src/main/js/response.js~resoptions#statuscode",
    "class/src/main/js/response.js~ResOptions.html#instance-member-statusCode",
    "src/main/js/response.js~ResOptions#statusCode",
    "member"
  ],
  [
    "src/main/js/response.js~response#_headers",
    "class/src/main/js/response.js~Response.html#instance-member-_headers",
    "src/main/js/response.js~Response#_headers",
    "member"
  ],
  [
    "src/main/js/response.js~response#app",
    "class/src/main/js/response.js~Response.html#instance-member-app",
    "src/main/js/response.js~Response#app",
    "member"
  ],
  [
    "src/main/js/response.js~response#constructor",
    "class/src/main/js/response.js~Response.html#instance-constructor-constructor",
    "src/main/js/response.js~Response#constructor",
    "method"
  ],
  [
    "src/main/js/response.js~response#end",
    "class/src/main/js/response.js~Response.html#instance-member-end",
    "src/main/js/response.js~Response#end",
    "member"
  ],
  [
    "src/main/js/response.js~response#req",
    "class/src/main/js/response.js~Response.html#instance-member-req",
    "src/main/js/response.js~Response#req",
    "member"
  ],
  [
    "src/main/js/response.js~response#write",
    "class/src/main/js/response.js~Response.html#instance-member-write",
    "src/main/js/response.js~Response#write",
    "member"
  ],
  [
    "src/main/js/util.js",
    "file/src/main/js/util.js.html",
    "src/main/js/util.js",
    "file"
  ],
  [
    "src/test/js/index.js",
    "file/src/test/js/index.js.html",
    "src/test/js/index.js",
    "file"
  ],
  [
    "src/test/js/reqresnext.js",
    "file/src/test/js/reqresnext.js.html",
    "src/test/js/reqresnext.js",
    "file"
  ],
  [
    "src/test/js/request.js",
    "file/src/test/js/request.js.html",
    "src/test/js/request.js",
    "file"
  ],
  [
    "src/test/js/response.js",
    "file/src/test/js/response.js.html",
    "src/test/js/response.js",
    "file"
  ]
]